# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgCalculateUrban.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgCalculateUrban(object):
    def setupUi(self, DlgCalculateUrban):
        DlgCalculateUrban.setObjectName("DlgCalculateUrban")
        DlgCalculateUrban.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgCalculateUrban.resize(300, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgCalculateUrban.sizePolicy().hasHeightForWidth())
        DlgCalculateUrban.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DlgCalculateUrban)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(DlgCalculateUrban)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_calculate_urban_change = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_calculate_urban_change.sizePolicy().hasHeightForWidth())
        self.btn_calculate_urban_change.setSizePolicy(sizePolicy)
        self.btn_calculate_urban_change.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_calculate_urban_change.setFont(font)
        self.btn_calculate_urban_change.setObjectName("btn_calculate_urban_change")
        self.verticalLayout_3.addWidget(self.btn_calculate_urban_change)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(DlgCalculateUrban)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_summary_single_polygon = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_summary_single_polygon.sizePolicy().hasHeightForWidth())
        self.btn_summary_single_polygon.setSizePolicy(sizePolicy)
        self.btn_summary_single_polygon.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_summary_single_polygon.setFont(font)
        self.btn_summary_single_polygon.setObjectName("btn_summary_single_polygon")
        self.verticalLayout.addWidget(self.btn_summary_single_polygon)
        self.verticalLayout_2.addWidget(self.groupBox_4)

        self.retranslateUi(DlgCalculateUrban)
        QtCore.QMetaObject.connectSlotsByName(DlgCalculateUrban)

    def retranslateUi(self, DlgCalculateUrban):
        _translate = QtCore.QCoreApplication.translate
        DlgCalculateUrban.setWindowTitle(_translate("DlgCalculateUrban", "Calculate Urban Change Indicators"))
        self.groupBox.setTitle(_translate("DlgCalculateUrban", "Step 1: Calculate urban change"))
        self.btn_calculate_urban_change.setText(_translate("DlgCalculateUrban", "Calculate urban change spatial layers"))
        self.groupBox_4.setTitle(_translate("DlgCalculateUrban", "Step 2: Calculate urban change summary table"))
        self.btn_summary_single_polygon.setText(_translate("DlgCalculateUrban", "Calculate urban change summary table for city"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgCalculateUrban = QtWidgets.QDialog()
    ui = Ui_DlgCalculateUrban()
    ui.setupUi(DlgCalculateUrban)
    DlgCalculateUrban.show()
    sys.exit(app.exec_())
