# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgCalculateRestBiomass.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgCalculateRestBiomass(object):
    def setupUi(self, DlgCalculateRestBiomass):
        DlgCalculateRestBiomass.setObjectName("DlgCalculateRestBiomass")
        DlgCalculateRestBiomass.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgCalculateRestBiomass.resize(398, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgCalculateRestBiomass.sizePolicy().hasHeightForWidth())
        DlgCalculateRestBiomass.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DlgCalculateRestBiomass)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(DlgCalculateRestBiomass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_calculate_rest_biomass_change = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_calculate_rest_biomass_change.sizePolicy().hasHeightForWidth())
        self.btn_calculate_rest_biomass_change.setSizePolicy(sizePolicy)
        self.btn_calculate_rest_biomass_change.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_calculate_rest_biomass_change.setFont(font)
        self.btn_calculate_rest_biomass_change.setObjectName("btn_calculate_rest_biomass_change")
        self.verticalLayout_3.addWidget(self.btn_calculate_rest_biomass_change)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(DlgCalculateRestBiomass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_summary_single_polygon = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_summary_single_polygon.sizePolicy().hasHeightForWidth())
        self.btn_summary_single_polygon.setSizePolicy(sizePolicy)
        self.btn_summary_single_polygon.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_summary_single_polygon.setFont(font)
        self.btn_summary_single_polygon.setObjectName("btn_summary_single_polygon")
        self.verticalLayout.addWidget(self.btn_summary_single_polygon)
        self.verticalLayout_2.addWidget(self.groupBox_4)

        self.retranslateUi(DlgCalculateRestBiomass)
        QtCore.QMetaObject.connectSlotsByName(DlgCalculateRestBiomass)

    def retranslateUi(self, DlgCalculateRestBiomass):
        _translate = QtCore.QCoreApplication.translate
        DlgCalculateRestBiomass.setWindowTitle(_translate("DlgCalculateRestBiomass", "Estimate Likely Change in Biomass Due to Restoration"))
        self.groupBox.setTitle(_translate("DlgCalculateRestBiomass", "Step 1: Estimate likely change in biomass from restoration"))
        self.btn_calculate_rest_biomass_change.setText(_translate("DlgCalculateRestBiomass", "Estimate biomass change due to restoration"))
        self.groupBox_4.setTitle(_translate("DlgCalculateRestBiomass", "Step 2: Calculate biomass change summary table"))
        self.btn_summary_single_polygon.setText(_translate("DlgCalculateRestBiomass", "Calculate table summarizing likely changes in biomass due to restoration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgCalculateRestBiomass = QtWidgets.QDialog()
    ui = Ui_DlgCalculateRestBiomass()
    ui.setupUi(DlgCalculateRestBiomass)
    DlgCalculateRestBiomass.show()
    sys.exit(app.exec_())
