# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgCalculateForest.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgCalculateForest(object):
    def setupUi(self, DlgCalculateForest):
        DlgCalculateForest.setObjectName("DlgCalculateForest")
        DlgCalculateForest.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgCalculateForest.resize(418, 198)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgCalculateForest.sizePolicy().hasHeightForWidth())
        DlgCalculateForest.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DlgCalculateForest)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(DlgCalculateForest)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_tc = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_tc.setGeometry(QtCore.QRect(70, 50, 271, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_tc.setFont(font)
        self.pushButton_tc.setObjectName("pushButton_tc")
        self.pushButton_ff = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ff.setGeometry(QtCore.QRect(70, 110, 271, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ff.setFont(font)
        self.pushButton_ff.setObjectName("pushButton_ff")
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(DlgCalculateForest)
        QtCore.QMetaObject.connectSlotsByName(DlgCalculateForest)

    def retranslateUi(self, DlgCalculateForest):
        _translate = QtCore.QCoreApplication.translate
        DlgCalculateForest.setWindowTitle(_translate("DlgCalculateForest", "Calculate Forest Degradation Indicators"))
        self.groupBox.setTitle(_translate("DlgCalculateForest", "Forest Degradation Hotspots Indicators"))
        self.pushButton_tc.setText(_translate("DlgCalculateForest", "Forest Change and Total Carbon"))
        self.pushButton_ff.setText(_translate("DlgCalculateForest", "Forest Fires"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgCalculateForest = QtWidgets.QDialog()
    ui = Ui_DlgCalculateForest()
    ui.setupUi(DlgCalculateForest)
    DlgCalculateForest.show()
    sys.exit(app.exec_())
