# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgDataIOImportCQI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgDataIOImportCQI(object):
    def setupUi(self, DlgDataIOImportCQI):
        DlgDataIOImportCQI.setObjectName("DlgDataIOImportCQI")
        DlgDataIOImportCQI.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgDataIOImportCQI.resize(385, 50)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgDataIOImportCQI.sizePolicy().hasHeightForWidth())
        DlgDataIOImportCQI.setSizePolicy(sizePolicy)
        DlgDataIOImportCQI.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgDataIOImportCQI)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnBox = QtWidgets.QDialogButtonBox(DlgDataIOImportCQI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBox.sizePolicy().hasHeightForWidth())
        self.btnBox.setSizePolicy(sizePolicy)
        self.btnBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBox.setObjectName("btnBox")
        self.verticalLayout.addWidget(self.btnBox)

        self.retranslateUi(DlgDataIOImportCQI)
        self.btnBox.accepted.connect(DlgDataIOImportCQI.accept)
        self.btnBox.rejected.connect(DlgDataIOImportCQI.reject)
        QtCore.QMetaObject.connectSlotsByName(DlgDataIOImportCQI)

    def retranslateUi(self, DlgDataIOImportCQI):
        _translate = QtCore.QCoreApplication.translate
        DlgDataIOImportCQI.setWindowTitle(_translate("DlgDataIOImportCQI", "Load a Custom Climate Quality Dataset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgDataIOImportCQI = QtWidgets.QDialog()
    ui = Ui_DlgDataIOImportCQI()
    ui.setupUi(DlgDataIOImportCQI)
    DlgDataIOImportCQI.show()
    sys.exit(app.exec_())
