# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgDataIOLoadTE.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgDataIOLoadTE(object):
    def setupUi(self, DlgDataIOLoadTE):
        DlgDataIOLoadTE.setObjectName("DlgDataIOLoadTE")
        DlgDataIOLoadTE.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgDataIOLoadTE.resize(294, 377)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgDataIOLoadTE.sizePolicy().hasHeightForWidth())
        DlgDataIOLoadTE.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(DlgDataIOLoadTE)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(DlgDataIOLoadTE)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(DlgDataIOLoadTE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layers_view = QtWidgets.QListView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layers_view.sizePolicy().hasHeightForWidth())
        self.layers_view.setSizePolicy(sizePolicy)
        self.layers_view.setMinimumSize(QtCore.QSize(200, 150))
        self.layers_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.layers_view.setObjectName("layers_view")
        self.verticalLayout_2.addWidget(self.layers_view)
        self.btn_view_metadata = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_view_metadata.sizePolicy().hasHeightForWidth())
        self.btn_view_metadata.setSizePolicy(sizePolicy)
        self.btn_view_metadata.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_view_metadata.setObjectName("btn_view_metadata")
        self.verticalLayout_2.addWidget(self.btn_view_metadata)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.data_file_box = QtWidgets.QGroupBox(DlgDataIOLoadTE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_file_box.sizePolicy().hasHeightForWidth())
        self.data_file_box.setSizePolicy(sizePolicy)
        self.data_file_box.setObjectName("data_file_box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.data_file_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_lineedit = QtWidgets.QLineEdit(self.data_file_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_lineedit.sizePolicy().hasHeightForWidth())
        self.file_lineedit.setSizePolicy(sizePolicy)
        self.file_lineedit.setMinimumSize(QtCore.QSize(0, 30))
        self.file_lineedit.setReadOnly(True)
        self.file_lineedit.setObjectName("file_lineedit")
        self.horizontalLayout.addWidget(self.file_lineedit)
        self.file_browse_btn = QtWidgets.QPushButton(self.data_file_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_browse_btn.sizePolicy().hasHeightForWidth())
        self.file_browse_btn.setSizePolicy(sizePolicy)
        self.file_browse_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.file_browse_btn.setObjectName("file_browse_btn")
        self.horizontalLayout.addWidget(self.file_browse_btn)
        self.gridLayout.addWidget(self.data_file_box, 0, 0, 1, 1)

        self.retranslateUi(DlgDataIOLoadTE)
        QtCore.QMetaObject.connectSlotsByName(DlgDataIOLoadTE)

    def retranslateUi(self, DlgDataIOLoadTE):
        _translate = QtCore.QCoreApplication.translate
        DlgDataIOLoadTE.setWindowTitle(_translate("DlgDataIOLoadTE", "Open a MISLAND file"))
        self.groupBox.setTitle(_translate("DlgDataIOLoadTE", "Select a layer(s)"))
        self.btn_view_metadata.setText(_translate("DlgDataIOLoadTE", "View file metadata"))
        self.data_file_box.setTitle(_translate("DlgDataIOLoadTE", "Select a file"))
        self.file_lineedit.setPlaceholderText(_translate("DlgDataIOLoadTE", "Click \"Browse\" to choose a file..."))
        self.file_browse_btn.setText(_translate("DlgDataIOLoadTE", "Browse..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgDataIOLoadTE = QtWidgets.QDialog()
    ui = Ui_DlgDataIOLoadTE()
    ui.setupUi(DlgDataIOLoadTE)
    DlgDataIOLoadTE.show()
    sys.exit(app.exec_())
