# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgDataIOImportSOC.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgDataIOImportSOC(object):
    def setupUi(self, DlgDataIOImportSOC):
        DlgDataIOImportSOC.setObjectName("DlgDataIOImportSOC")
        DlgDataIOImportSOC.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgDataIOImportSOC.resize(466, 41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgDataIOImportSOC.sizePolicy().hasHeightForWidth())
        DlgDataIOImportSOC.setSizePolicy(sizePolicy)
        DlgDataIOImportSOC.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgDataIOImportSOC)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnBox = QtWidgets.QDialogButtonBox(DlgDataIOImportSOC)
        self.btnBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBox.setObjectName("btnBox")
        self.verticalLayout.addWidget(self.btnBox)

        self.retranslateUi(DlgDataIOImportSOC)
        self.btnBox.accepted.connect(DlgDataIOImportSOC.accept)
        self.btnBox.rejected.connect(DlgDataIOImportSOC.reject)
        QtCore.QMetaObject.connectSlotsByName(DlgDataIOImportSOC)

    def retranslateUi(self, DlgDataIOImportSOC):
        _translate = QtCore.QCoreApplication.translate
        DlgDataIOImportSOC.setWindowTitle(_translate("DlgDataIOImportSOC", "Load a Custom Soil Organic Carbon (SOC) dataset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgDataIOImportSOC = QtWidgets.QDialog()
    ui = Ui_DlgDataIOImportSOC()
    ui.setupUi(DlgDataIOImportSOC)
    DlgDataIOImportSOC.show()
    sys.exit(app.exec_())
