# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgDataIOImportLC.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgDataIOImportLC(object):
    def setupUi(self, DlgDataIOImportLC):
        DlgDataIOImportLC.setObjectName("DlgDataIOImportLC")
        DlgDataIOImportLC.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgDataIOImportLC.resize(366, 257)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgDataIOImportLC.sizePolicy().hasHeightForWidth())
        DlgDataIOImportLC.setSizePolicy(sizePolicy)
        DlgDataIOImportLC.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgDataIOImportLC)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_lc_agg = QtWidgets.QGroupBox(DlgDataIOImportLC)
        self.groupBox_lc_agg.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_lc_agg.sizePolicy().hasHeightForWidth())
        self.groupBox_lc_agg.setSizePolicy(sizePolicy)
        self.groupBox_lc_agg.setObjectName("groupBox_lc_agg")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_lc_agg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_agg_edit_def = QtWidgets.QPushButton(self.groupBox_lc_agg)
        self.btn_agg_edit_def.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_agg_edit_def.sizePolicy().hasHeightForWidth())
        self.btn_agg_edit_def.setSizePolicy(sizePolicy)
        self.btn_agg_edit_def.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_agg_edit_def.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_agg_edit_def.setObjectName("btn_agg_edit_def")
        self.verticalLayout_2.addWidget(self.btn_agg_edit_def)
        self.checkBox_use_sample = QtWidgets.QCheckBox(self.groupBox_lc_agg)
        self.checkBox_use_sample.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_use_sample.sizePolicy().hasHeightForWidth())
        self.checkBox_use_sample.setSizePolicy(sizePolicy)
        self.checkBox_use_sample.setChecked(True)
        self.checkBox_use_sample.setObjectName("checkBox_use_sample")
        self.verticalLayout_2.addWidget(self.checkBox_use_sample)
        self.checkBox_use_sample_description = QtWidgets.QLabel(self.groupBox_lc_agg)
        self.checkBox_use_sample_description.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_use_sample_description.sizePolicy().hasHeightForWidth())
        self.checkBox_use_sample_description.setSizePolicy(sizePolicy)
        self.checkBox_use_sample_description.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_use_sample_description.setBaseSize(QtCore.QSize(0, 0))
        self.checkBox_use_sample_description.setWordWrap(True)
        self.checkBox_use_sample_description.setObjectName("checkBox_use_sample_description")
        self.verticalLayout_2.addWidget(self.checkBox_use_sample_description)
        self.verticalLayout.addWidget(self.groupBox_lc_agg)
        self.btnBox = QtWidgets.QDialogButtonBox(DlgDataIOImportLC)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBox.sizePolicy().hasHeightForWidth())
        self.btnBox.setSizePolicy(sizePolicy)
        self.btnBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBox.setObjectName("btnBox")
        self.verticalLayout.addWidget(self.btnBox)

        self.retranslateUi(DlgDataIOImportLC)
        self.btnBox.accepted.connect(DlgDataIOImportLC.accept)
        self.btnBox.rejected.connect(DlgDataIOImportLC.reject)
        QtCore.QMetaObject.connectSlotsByName(DlgDataIOImportLC)

    def retranslateUi(self, DlgDataIOImportLC):
        _translate = QtCore.QCoreApplication.translate
        DlgDataIOImportLC.setWindowTitle(_translate("DlgDataIOImportLC", "Load a Custom Land Cover Dataset"))
        self.groupBox_lc_agg.setTitle(_translate("DlgDataIOImportLC", "Choose a land cover aggregation method"))
        self.btn_agg_edit_def.setText(_translate("DlgDataIOImportLC", "Edit definition"))
        self.checkBox_use_sample.setText(_translate("DlgDataIOImportLC", "Use sample when reading cover classes from input file"))
        self.checkBox_use_sample_description.setText(_translate("DlgDataIOImportLC", "Note: If reading a large file it is recommended that the above option be checked, as it will significantly speed the process of reading the input classes from the dataset. However, if you find that MISLAND is not identifying all of the classes in the input file, it may be necessary to turn off this option. (Applies only if raster input is chosen)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgDataIOImportLC = QtWidgets.QDialog()
    ui = Ui_DlgDataIOImportLC()
    ui.setupUi(DlgDataIOImportLC)
    DlgDataIOImportLC.show()
    sys.exit(app.exec_())
