# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgDataIOImportMedalus.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgDataIOImportMedalus(object):
    def setupUi(self, DlgDataIOImportMedalus):
        DlgDataIOImportMedalus.setObjectName("DlgDataIOImportMedalus")
        DlgDataIOImportMedalus.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgDataIOImportMedalus.resize(302, 289)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgDataIOImportMedalus.sizePolicy().hasHeightForWidth())
        DlgDataIOImportMedalus.setSizePolicy(sizePolicy)
        DlgDataIOImportMedalus.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgDataIOImportMedalus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_lc_agg = QtWidgets.QGroupBox(DlgDataIOImportMedalus)
        self.groupBox_lc_agg.setEnabled(True)
        self.groupBox_lc_agg.setObjectName("groupBox_lc_agg")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_lc_agg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_lc_agg)
        self.textBrowser.setMinimumSize(QtCore.QSize(200, 120))
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_lc_agg)
        self.btnBox = QtWidgets.QDialogButtonBox(DlgDataIOImportMedalus)
        self.btnBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBox.setObjectName("btnBox")
        self.verticalLayout.addWidget(self.btnBox)

        self.retranslateUi(DlgDataIOImportMedalus)
        self.btnBox.accepted.connect(DlgDataIOImportMedalus.accept)
        self.btnBox.rejected.connect(DlgDataIOImportMedalus.reject)
        QtCore.QMetaObject.connectSlotsByName(DlgDataIOImportMedalus)

    def retranslateUi(self, DlgDataIOImportMedalus):
        _translate = QtCore.QCoreApplication.translate
        DlgDataIOImportMedalus.setWindowTitle(_translate("DlgDataIOImportMedalus", "Load a Custom Medalus Subindicator Dataset"))
        self.groupBox_lc_agg.setTitle(_translate("DlgDataIOImportMedalus", "Class definition"))
        self.textBrowser.setHtml(_translate("DlgDataIOImportMedalus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Classes in the input data must be coded as follows: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">1: Good Quality </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">2: Moderate Quality </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">3: Low Quality </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">0 or -32768: No data</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgDataIOImportMedalus = QtWidgets.QDialog()
    ui = Ui_DlgDataIOImportMedalus()
    ui.setupUi(DlgDataIOImportMedalus)
    DlgDataIOImportMedalus.show()
    sys.exit(app.exec_())
