# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgJobs.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgJobs(object):
    def setupUi(self, DlgJobs):
        DlgJobs.setObjectName("DlgJobs")
        DlgJobs.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgJobs.resize(900, 310)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgJobs.sizePolicy().hasHeightForWidth())
        DlgJobs.setSizePolicy(sizePolicy)
        DlgJobs.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(DlgJobs)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(DlgJobs)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.jobs_view = QtWidgets.QTableView(DlgJobs)
        self.jobs_view.setMinimumSize(QtCore.QSize(600, 200))
        self.jobs_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.jobs_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.jobs_view.setSortingEnabled(True)
        self.jobs_view.setObjectName("jobs_view")
        self.jobs_view.horizontalHeader().setVisible(True)
        self.jobs_view.horizontalHeader().setCascadingSectionResizes(True)
        self.jobs_view.horizontalHeader().setStretchLastSection(True)
        self.jobs_view.verticalHeader().setVisible(False)
        self.jobs_view.verticalHeader().setSortIndicatorShown(True)
        self.gridLayout.addWidget(self.jobs_view, 1, 0, 1, 1)
        self.download = QtWidgets.QPushButton(DlgJobs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download.sizePolicy().hasHeightForWidth())
        self.download.setSizePolicy(sizePolicy)
        self.download.setMinimumSize(QtCore.QSize(0, 30))
        self.download.setObjectName("download")
        self.gridLayout.addWidget(self.download, 3, 0, 1, 1)
        self.refresh = QtWidgets.QPushButton(DlgJobs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh.sizePolicy().hasHeightForWidth())
        self.refresh.setSizePolicy(sizePolicy)
        self.refresh.setMinimumSize(QtCore.QSize(0, 30))
        self.refresh.setObjectName("refresh")
        self.gridLayout.addWidget(self.refresh, 2, 0, 1, 1)

        self.retranslateUi(DlgJobs)
        QtCore.QMetaObject.connectSlotsByName(DlgJobs)

    def retranslateUi(self, DlgJobs):
        _translate = QtCore.QCoreApplication.translate
        DlgJobs.setWindowTitle(_translate("DlgJobs", "Download results from Earth Engine"))
        self.label.setText(_translate("DlgJobs", "Jobs expire 2 days after they are submitted. After a job has expired, it will no longer appear in this list."))
        self.download.setText(_translate("DlgJobs", "Download results"))
        self.refresh.setText(_translate("DlgJobs", "Refresh list"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgJobs = QtWidgets.QDialog()
    ui = Ui_DlgJobs()
    ui.setupUi(DlgJobs)
    DlgJobs.show()
    sys.exit(app.exec_())
