# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgPlot.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgPlot(object):
    def setupUi(self, DlgPlot):
        DlgPlot.setObjectName("DlgPlot")
        DlgPlot.resize(518, 356)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgPlot.sizePolicy().hasHeightForWidth())
        DlgPlot.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgPlot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plot_window = PlotWidget(DlgPlot)
        self.plot_window.setMinimumSize(QtCore.QSize(500, 300))
        self.plot_window.setObjectName("plot_window")
        self.verticalLayout.addWidget(self.plot_window)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.save_image = QtWidgets.QPushButton(DlgPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_image.sizePolicy().hasHeightForWidth())
        self.save_image.setSizePolicy(sizePolicy)
        self.save_image.setMinimumSize(QtCore.QSize(0, 30))
        self.save_image.setObjectName("save_image")
        self.gridLayout.addWidget(self.save_image, 0, 0, 1, 1)
        self.save_data = QtWidgets.QPushButton(DlgPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_data.sizePolicy().hasHeightForWidth())
        self.save_data.setSizePolicy(sizePolicy)
        self.save_data.setMinimumSize(QtCore.QSize(0, 30))
        self.save_data.setObjectName("save_data")
        self.gridLayout.addWidget(self.save_data, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(DlgPlot)
        QtCore.QMetaObject.connectSlotsByName(DlgPlot)

    def retranslateUi(self, DlgPlot):
        _translate = QtCore.QCoreApplication.translate
        DlgPlot.setWindowTitle(_translate("DlgPlot", "MISLAND plot"))
        self.save_image.setText(_translate("DlgPlot", "Save image"))
        self.save_data.setText(_translate("DlgPlot", "Save data"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgPlot = QtWidgets.QDialog()
    ui = Ui_DlgPlot()
    ui.setupUi(DlgPlot)
    DlgPlot.show()
    sys.exit(app.exec_())
