# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgVisualization.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgVisualization(object):
    def setupUi(self, DlgVisualization):
        DlgVisualization.setObjectName("DlgVisualization")
        DlgVisualization.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgVisualization.resize(200, 124)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgVisualization.sizePolicy().hasHeightForWidth())
        DlgVisualization.setSizePolicy(sizePolicy)
        DlgVisualization.setMinimumSize(QtCore.QSize(200, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgVisualization)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DlgVisualization)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_basemap = QtWidgets.QPushButton(DlgVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_basemap.sizePolicy().hasHeightForWidth())
        self.btn_basemap.setSizePolicy(sizePolicy)
        self.btn_basemap.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_basemap.setObjectName("btn_basemap")
        self.verticalLayout.addWidget(self.btn_basemap)
        self.btn_create_map = QtWidgets.QPushButton(DlgVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_create_map.sizePolicy().hasHeightForWidth())
        self.btn_create_map.setSizePolicy(sizePolicy)
        self.btn_create_map.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_create_map.setObjectName("btn_create_map")
        self.verticalLayout.addWidget(self.btn_create_map)

        self.retranslateUi(DlgVisualization)
        QtCore.QMetaObject.connectSlotsByName(DlgVisualization)

    def retranslateUi(self, DlgVisualization):
        _translate = QtCore.QCoreApplication.translate
        DlgVisualization.setWindowTitle(_translate("DlgVisualization", "Visualization tools"))
        self.label.setText(_translate("DlgVisualization", "Visualization tools:"))
        self.btn_basemap.setText(_translate("DlgVisualization", "Add Basemap"))
        self.btn_create_map.setText(_translate("DlgVisualization", "Create Print Map"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgVisualization = QtWidgets.QDialog()
    ui = Ui_DlgVisualization()
    ui.setupUi(DlgVisualization)
    DlgVisualization.show()
    sys.exit(app.exec_())
