# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\WidgetDataIOSelectTELayerExisting.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetDataIOSelectTELayerExisting(object):
    def setupUi(self, WidgetDataIOSelectTELayerExisting):
        WidgetDataIOSelectTELayerExisting.setObjectName("WidgetDataIOSelectTELayerExisting")
        WidgetDataIOSelectTELayerExisting.resize(330, 33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetDataIOSelectTELayerExisting.sizePolicy().hasHeightForWidth())
        WidgetDataIOSelectTELayerExisting.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(WidgetDataIOSelectTELayerExisting)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_layers = QtWidgets.QComboBox(WidgetDataIOSelectTELayerExisting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_layers.sizePolicy().hasHeightForWidth())
        self.comboBox_layers.setSizePolicy(sizePolicy)
        self.comboBox_layers.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_layers.setObjectName("comboBox_layers")
        self.horizontalLayout.addWidget(self.comboBox_layers)
        self.pushButton_load_existing = QtWidgets.QPushButton(WidgetDataIOSelectTELayerExisting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load_existing.sizePolicy().hasHeightForWidth())
        self.pushButton_load_existing.setSizePolicy(sizePolicy)
        self.pushButton_load_existing.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_load_existing.setObjectName("pushButton_load_existing")
        self.horizontalLayout.addWidget(self.pushButton_load_existing)

        self.retranslateUi(WidgetDataIOSelectTELayerExisting)
        QtCore.QMetaObject.connectSlotsByName(WidgetDataIOSelectTELayerExisting)

    def retranslateUi(self, WidgetDataIOSelectTELayerExisting):
        _translate = QtCore.QCoreApplication.translate
        WidgetDataIOSelectTELayerExisting.setWindowTitle(_translate("WidgetDataIOSelectTELayerExisting", "Form"))
        self.pushButton_load_existing.setText(_translate("WidgetDataIOSelectTELayerExisting", "Load existing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetDataIOSelectTELayerExisting = QtWidgets.QWidget()
    ui = Ui_WidgetDataIOSelectTELayerExisting()
    ui.setupUi(WidgetDataIOSelectTELayerExisting)
    WidgetDataIOSelectTELayerExisting.show()
    sys.exit(app.exec_())
