# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\WidgetMQISetup.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetMQISetup(object):
    def setupUi(self, WidgetMQISetup):
        WidgetMQISetup.setObjectName("WidgetMQISetup")
        WidgetMQISetup.resize(384, 453)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetMQISetup.sizePolicy().hasHeightForWidth())
        WidgetMQISetup.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetMQISetup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(WidgetMQISetup)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 70))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.groupBox_usda_depth = QtWidgets.QGroupBox(WidgetMQISetup)
        self.groupBox_usda_depth.setEnabled(True)
        self.groupBox_usda_depth.setObjectName("groupBox_usda_depth")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_usda_depth)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_usda_depth)
        self.label_10.setMinimumSize(QtCore.QSize(30, 30))
        self.label_10.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.use_esa_tg_year = QtWidgets.QDateEdit(self.groupBox_usda_depth)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_esa_tg_year.sizePolicy().hasHeightForWidth())
        self.use_esa_tg_year.setSizePolicy(sizePolicy)
        self.use_esa_tg_year.setMinimumSize(QtCore.QSize(0, 30))
        self.use_esa_tg_year.setMaximumSize(QtCore.QSize(120, 35))
        self.use_esa_tg_year.setMaximumDate(QtCore.QDate(2018, 12, 31))
        self.use_esa_tg_year.setMinimumDate(QtCore.QDate(1992, 1, 1))
        self.use_esa_tg_year.setDisplayFormat("yyyy")
        self.use_esa_tg_year.setDate(QtCore.QDate(2001, 1, 1))
        self.use_esa_tg_year.setObjectName("use_esa_tg_year")
        self.gridLayout_3.addWidget(self.use_esa_tg_year, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_usda_depth)
        self.groupBox_lu_agg = QtWidgets.QGroupBox(WidgetMQISetup)
        self.groupBox_lu_agg.setObjectName("groupBox_lu_agg")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_lu_agg)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.use_lu_agg_edit = QtWidgets.QPushButton(self.groupBox_lu_agg)
        self.use_lu_agg_edit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_lu_agg_edit.sizePolicy().hasHeightForWidth())
        self.use_lu_agg_edit.setSizePolicy(sizePolicy)
        self.use_lu_agg_edit.setMinimumSize(QtCore.QSize(100, 30))
        self.use_lu_agg_edit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.use_lu_agg_edit.setCheckable(False)
        self.use_lu_agg_edit.setObjectName("use_lu_agg_edit")
        self.gridLayout_7.addWidget(self.use_lu_agg_edit, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_lu_agg)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(WidgetMQISetup)
        QtCore.QMetaObject.connectSlotsByName(WidgetMQISetup)

    def retranslateUi(self, WidgetMQISetup):
        _translate = QtCore.QCoreApplication.translate
        WidgetMQISetup.setWindowTitle(_translate("WidgetMQISetup", "Form"))
        self.textBrowser.setHtml(_translate("WidgetMQISetup", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-size:8pt; background-color:#ffffff;\">The formula used to compute the MQI is as shown below:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-size:8pt; font-weight:600; background-color:#ffffff;\">MQI</span><span style=\" font-size:8pt; background-color:#ffffff;\">  =(land use intensity * population density) ^1/2</span></p></body></html>"))
        self.groupBox_usda_depth.setTitle(_translate("WidgetMQISetup", "Land Cover Year (ESA CCI) (1992 TO 2018)"))
        self.label_10.setText(_translate("WidgetMQISetup", "Target Year: "))
        self.groupBox_lu_agg.setTitle(_translate("WidgetMQISetup", "Customize land use intenisty aggregation method"))
        self.use_lu_agg_edit.setText(_translate("WidgetMQISetup", "Edit definition"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetMQISetup = QtWidgets.QWidget()
    ui = Ui_WidgetMQISetup()
    ui.setupUi(WidgetMQISetup)
    WidgetMQISetup.show()
    sys.exit(app.exec_())
