# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\WidgetDataIOImportSelectRasterOutput.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetDataIOImportSelectRasterOutput(object):
    def setupUi(self, WidgetDataIOImportSelectRasterOutput):
        WidgetDataIOImportSelectRasterOutput.setObjectName("WidgetDataIOImportSelectRasterOutput")
        WidgetDataIOImportSelectRasterOutput.resize(469, 81)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetDataIOImportSelectRasterOutput)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(WidgetDataIOImportSelectRasterOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_output_file = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_output_file.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_output_file.sizePolicy().hasHeightForWidth())
        self.lineEdit_output_file.setSizePolicy(sizePolicy)
        self.lineEdit_output_file.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_output_file.setReadOnly(True)
        self.lineEdit_output_file.setObjectName("lineEdit_output_file")
        self.gridLayout.addWidget(self.lineEdit_output_file, 0, 0, 1, 1)
        self.btn_output_file_browse = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_output_file_browse.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_output_file_browse.sizePolicy().hasHeightForWidth())
        self.btn_output_file_browse.setSizePolicy(sizePolicy)
        self.btn_output_file_browse.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_output_file_browse.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_output_file_browse.setObjectName("btn_output_file_browse")
        self.gridLayout.addWidget(self.btn_output_file_browse, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)

        self.retranslateUi(WidgetDataIOImportSelectRasterOutput)
        QtCore.QMetaObject.connectSlotsByName(WidgetDataIOImportSelectRasterOutput)

    def retranslateUi(self, WidgetDataIOImportSelectRasterOutput):
        _translate = QtCore.QCoreApplication.translate
        WidgetDataIOImportSelectRasterOutput.setWindowTitle(_translate("WidgetDataIOImportSelectRasterOutput", "Form"))
        self.groupBox_4.setTitle(_translate("WidgetDataIOImportSelectRasterOutput", "Output raster file (.tif)"))
        self.lineEdit_output_file.setPlaceholderText(_translate("WidgetDataIOImportSelectRasterOutput", "Click \"Browse\" to choose a file..."))
        self.btn_output_file_browse.setText(_translate("WidgetDataIOImportSelectRasterOutput", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetDataIOImportSelectRasterOutput = QtWidgets.QWidget()
    ui = Ui_WidgetDataIOImportSelectRasterOutput()
    ui.setupUi(WidgetDataIOImportSelectRasterOutput)
    WidgetDataIOImportSelectRasterOutput.show()
    sys.exit(app.exec_())
