# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\WidgetCalculationOutput.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetCalculationOutput(object):
    def setupUi(self, WidgetCalculationOutput):
        WidgetCalculationOutput.setObjectName("WidgetCalculationOutput")
        WidgetCalculationOutput.resize(535, 416)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetCalculationOutput.sizePolicy().hasHeightForWidth())
        WidgetCalculationOutput.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetCalculationOutput)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(WidgetCalculationOutput)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.output_basename = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_basename.sizePolicy().hasHeightForWidth())
        self.output_basename.setSizePolicy(sizePolicy)
        self.output_basename.setMinimumSize(QtCore.QSize(0, 35))
        self.output_basename.setReadOnly(True)
        self.output_basename.setObjectName("output_basename")
        self.horizontalLayout_2.addWidget(self.output_basename)
        self.browse_output_basename = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_output_basename.sizePolicy().hasHeightForWidth())
        self.browse_output_basename.setSizePolicy(sizePolicy)
        self.browse_output_basename.setMinimumSize(QtCore.QSize(0, 35))
        self.browse_output_basename.setObjectName("browse_output_basename")
        self.horizontalLayout_2.addWidget(self.browse_output_basename)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox = QtWidgets.QGroupBox(WidgetCalculationOutput)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.output_summary = QtWidgets.QTextBrowser(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_summary.sizePolicy().hasHeightForWidth())
        self.output_summary.setSizePolicy(sizePolicy)
        self.output_summary.setObjectName("output_summary")
        self.verticalLayout_4.addWidget(self.output_summary)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(WidgetCalculationOutput)
        QtCore.QMetaObject.connectSlotsByName(WidgetCalculationOutput)

    def retranslateUi(self, WidgetCalculationOutput):
        _translate = QtCore.QCoreApplication.translate
        WidgetCalculationOutput.setWindowTitle(_translate("WidgetCalculationOutput", "Form"))
        self.groupBox_7.setTitle(_translate("WidgetCalculationOutput", "Base name used as prefix when naming output files"))
        self.output_basename.setPlaceholderText(_translate("WidgetCalculationOutput", "Click \"Browse\" to choose a base name..."))
        self.browse_output_basename.setText(_translate("WidgetCalculationOutput", "Browse"))
        self.groupBox.setTitle(_translate("WidgetCalculationOutput", "Output files that will be produced by this analysis"))
        self.output_summary.setHtml(_translate("WidgetCalculationOutput", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetCalculationOutput = QtWidgets.QWidget()
    ui = Ui_WidgetCalculationOutput()
    ui.setupUi(WidgetCalculationOutput)
    WidgetCalculationOutput.show()
    sys.exit(app.exec_())
