# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\WidgetDataIOSelectTELayerImport.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetDataIOSelectTELayerImport(object):
    def setupUi(self, WidgetDataIOSelectTELayerImport):
        WidgetDataIOSelectTELayerImport.setObjectName("WidgetDataIOSelectTELayerImport")
        WidgetDataIOSelectTELayerImport.resize(445, 30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetDataIOSelectTELayerImport.sizePolicy().hasHeightForWidth())
        WidgetDataIOSelectTELayerImport.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(WidgetDataIOSelectTELayerImport)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_layers = QtWidgets.QComboBox(WidgetDataIOSelectTELayerImport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_layers.sizePolicy().hasHeightForWidth())
        self.comboBox_layers.setSizePolicy(sizePolicy)
        self.comboBox_layers.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_layers.setObjectName("comboBox_layers")
        self.horizontalLayout.addWidget(self.comboBox_layers)
        self.pushButton_import = QtWidgets.QPushButton(WidgetDataIOSelectTELayerImport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_import.sizePolicy().hasHeightForWidth())
        self.pushButton_import.setSizePolicy(sizePolicy)
        self.pushButton_import.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_import.setObjectName("pushButton_import")
        self.horizontalLayout.addWidget(self.pushButton_import)
        self.pushButton_load_existing = QtWidgets.QPushButton(WidgetDataIOSelectTELayerImport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load_existing.sizePolicy().hasHeightForWidth())
        self.pushButton_load_existing.setSizePolicy(sizePolicy)
        self.pushButton_load_existing.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_load_existing.setObjectName("pushButton_load_existing")
        self.horizontalLayout.addWidget(self.pushButton_load_existing)

        self.retranslateUi(WidgetDataIOSelectTELayerImport)
        QtCore.QMetaObject.connectSlotsByName(WidgetDataIOSelectTELayerImport)

    def retranslateUi(self, WidgetDataIOSelectTELayerImport):
        _translate = QtCore.QCoreApplication.translate
        WidgetDataIOSelectTELayerImport.setWindowTitle(_translate("WidgetDataIOSelectTELayerImport", "Form"))
        self.pushButton_import.setText(_translate("WidgetDataIOSelectTELayerImport", "Import"))
        self.pushButton_load_existing.setText(_translate("WidgetDataIOSelectTELayerImport", "Load existing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetDataIOSelectTELayerImport = QtWidgets.QWidget()
    ui = Ui_WidgetDataIOSelectTELayerImport()
    ui.setupUi(WidgetDataIOSelectTELayerImport)
    WidgetDataIOSelectTELayerImport.show()
    sys.exit(app.exec_())
