# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\WidgetCQISetup.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetCQISetup(object):
    def setupUi(self, WidgetCQISetup):
        WidgetCQISetup.setObjectName("WidgetCQISetup")
        WidgetCQISetup.resize(781, 638)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetCQISetup.sizePolicy().hasHeightForWidth())
        WidgetCQISetup.setSizePolicy(sizePolicy)
        WidgetCQISetup.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetCQISetup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(WidgetCQISetup)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 90))
        self.textBrowser.setAutoFillBackground(True)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.use_default = QtWidgets.QRadioButton(WidgetCQISetup)
        self.use_default.setChecked(True)
        self.use_default.setObjectName("use_default")
        self.verticalLayout.addWidget(self.use_default)
        self.groupBox_default = QtWidgets.QGroupBox(WidgetCQISetup)
        self.groupBox_default.setEnabled(True)
        self.groupBox_default.setObjectName("groupBox_default")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_default)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_default)
        self.label_10.setMinimumSize(QtCore.QSize(30, 30))
        self.label_10.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.ecmwf_year = QtWidgets.QDateEdit(self.groupBox_default)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ecmwf_year.sizePolicy().hasHeightForWidth())
        self.ecmwf_year.setSizePolicy(sizePolicy)
        self.ecmwf_year.setMinimumSize(QtCore.QSize(30, 30))
        self.ecmwf_year.setMaximumSize(QtCore.QSize(500, 35))
        self.ecmwf_year.setMaximumDate(QtCore.QDate(2020, 6, 30))
        self.ecmwf_year.setMinimumDate(QtCore.QDate(1979, 1, 1))
        self.ecmwf_year.setDisplayFormat("yyyy")
        self.ecmwf_year.setCalendarPopup(False)
        self.ecmwf_year.setDate(QtCore.QDate(2001, 1, 1))
        self.ecmwf_year.setObjectName("ecmwf_year")
        self.gridLayout_2.addWidget(self.ecmwf_year, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_default)
        self.use_custom = QtWidgets.QRadioButton(WidgetCQISetup)
        font = QtGui.QFont()
        font.setItalic(True)
        self.use_custom.setFont(font)
        self.use_custom.setObjectName("use_custom")
        self.verticalLayout.addWidget(self.use_custom)
        self.groupBox_custom_ppt = QtWidgets.QGroupBox(WidgetCQISetup)
        self.groupBox_custom_ppt.setEnabled(True)
        self.groupBox_custom_ppt.setObjectName("groupBox_custom_ppt")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_custom_ppt)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.use_custom_ppt = WidgetDataIOSelectTELayerImport(self.groupBox_custom_ppt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_custom_ppt.sizePolicy().hasHeightForWidth())
        self.use_custom_ppt.setSizePolicy(sizePolicy)
        self.use_custom_ppt.setMinimumSize(QtCore.QSize(0, 30))
        self.use_custom_ppt.setProperty("layer_type", "Annual Precipitation (mm)")
        self.use_custom_ppt.setObjectName("use_custom_ppt")
        self.gridLayout_3.addWidget(self.use_custom_ppt, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_custom_ppt)
        self.groupBox_custom_pet = QtWidgets.QGroupBox(WidgetCQISetup)
        self.groupBox_custom_pet.setObjectName("groupBox_custom_pet")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_custom_pet)
        self.gridLayout.setObjectName("gridLayout")
        self.use_custom_pet = WidgetDataIOSelectTELayerImport(self.groupBox_custom_pet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_custom_pet.sizePolicy().hasHeightForWidth())
        self.use_custom_pet.setSizePolicy(sizePolicy)
        self.use_custom_pet.setMinimumSize(QtCore.QSize(0, 30))
        self.use_custom_pet.setProperty("layer_type", "Annual Evapotranspiration (mm)")
        self.use_custom_pet.setObjectName("use_custom_pet")
        self.gridLayout.addWidget(self.use_custom_pet, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_custom_pet)
        spacerItem = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.use_custom.raise_()
        self.groupBox_custom_ppt.raise_()
        self.use_default.raise_()
        self.groupBox_default.raise_()
        self.textBrowser.raise_()
        self.groupBox_custom_pet.raise_()

        self.retranslateUi(WidgetCQISetup)
        QtCore.QMetaObject.connectSlotsByName(WidgetCQISetup)

    def retranslateUi(self, WidgetCQISetup):
        _translate = QtCore.QCoreApplication.translate
        WidgetCQISetup.setWindowTitle(_translate("WidgetCQISetup", "Form"))
        self.textBrowser.setHtml(_translate("WidgetCQISetup", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This index is calculated using classifications of the following parameters: precipitation and aridity index.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">CQI = (precipitation*aridity)**1/2</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p></body></html>"))
        self.use_default.setText(_translate("WidgetCQISetup", "Default Misland Climate Quality data"))
        self.groupBox_default.setTitle(_translate("WidgetCQISetup", "Period (ranges from 1979-2020 )"))
        self.label_10.setText(_translate("WidgetCQISetup", "Target Year:"))
        self.use_custom.setText(_translate("WidgetCQISetup", "Custom Climate Quality datasets (*Beta version)"))
        self.groupBox_custom_ppt.setTitle(_translate("WidgetCQISetup", "Annual Mean Precipitation (mm)"))
        self.groupBox_custom_pet.setTitle(_translate("WidgetCQISetup", "Annual Mean Potential Evapotranspiration (mm)"))
from MISLAND.data_io import WidgetDataIOSelectTELayerImport


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetCQISetup = QtWidgets.QWidget()
    ui = Ui_WidgetCQISetup()
    ui.setupUi(WidgetCQISetup)
    WidgetCQISetup.show()
    sys.exit(app.exec_())
